services:
  app:
    image: wordpress:6.5.5
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - "./wordpress:/var/www/html"
      - "./theme:/var/www/html/wp-content/themes/${THEME_NAME}"
      - "./scripts:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
    depends_on:
      - db
    env_file:
      - .env
  db:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${MYSQL_HOST}
    hostname: ${MYSQL_HOST}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
