name: Deploy to FTP
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: DeployServer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Deploy Data
        run: sh ./scripts/export_all.sh

      - name: Check if Deploy Data Exists
        run: sh ./scripts/deploy_validator.sh

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./build/html/
