name: Deploy to FTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: DeployCoreServer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          server-dir: ${{ env.FTP_SERVER_DIR }}
          local-dir: ./src/
